import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'english' | 'hindi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  english: {
    // Navigation
    'navHome': 'Home',
    'navCrops': 'Crop & Irrigation',
    'navDisease': 'Disease Detection (AI)',
    'navCommunity': 'Community Hub',
    'navMarket': 'Market Prices',
    'navHelp': 'Help Center',
    'navAccount': 'Manage Account',
    'navSettings': 'Settings',
    'navLogout': 'Logout',
    'menu': 'Menu',

    // Dashboard
    'farmDashboard': 'Farm Dashboard',
    'weatherAQI': 'Weather & AQI',
    'soilHealth': 'Soil Health',
    'aiCropRec': 'AI Crop Recommendations',
    'rainfall': 'Rainfall',
    'aqi': 'AQI',
    'moistureLevel': 'Moisture Level',
    'fertilityIndex': 'Fertility Index',
    'viewLess': 'View Less',
    'viewAllRec': 'View All Recommendations',
    'selectSeason': 'Select Season',
    'summer': 'Summer',
    'monsoon': 'Monsoon',
    'winter': 'Winter',

    // Crops Page
    'cropIrrigationRec': 'Crop & Irrigation Recommendations',
    'currentSeasonCrops': 'Current Season Crops',
    'irrigationZones': 'Irrigation Zones',
    'growthTracking': 'Growth Tracking',
    'smartRec': 'Smart Recommendations',
    'match': 'Match',
    'suitability': 'Suitability',
    'nextWatering': 'Next watering',
    'adjust': 'Adjust',
    'active': 'Active',
    'scheduled': 'Scheduled',
    'manual': 'Manual',
    'yieldPrediction': 'Yield Prediction',
    'expectedHarvest': 'Expected harvest in',
    'days': 'days',
    'growthRate': 'Growth Rate',
    'healthScore': 'Health Score',
    'todaysAction': "Today's Action",
    'harvestReady': 'Harvest Ready',

    // Disease Detection
    'cropDiseaseDetection': 'Crop Disease Detection (AI)',
    'uploadImage': 'Upload Image',
    'clickToUpload': 'Click to upload or drag and drop',
    'supportsFormats': 'Supports JPG, PNG',
    'analyzeCrop': 'Analyze Crop',
    'analyzing': 'Analyzing...',
    'analysisResult': 'Analysis Result',
    'severity': 'Severity',
    'confidence': 'Confidence',
    'recommendedTreatment': 'Recommended Treatment',
    'disclaimer': 'Disclaimer: This is an AI simulation. Always consult an expert for critical decisions.',

    // Settings
    'settings': 'Settings',
    'appearanceLanguage': 'Appearance & Language',
    'unitsMeasurements': 'Units & Measurements',
    'appPreferences': 'App Preferences',
    'appTheme': 'App Theme',
    'selectTheme': 'Select your preferred display mode',
    'light': 'Light',
    'dark': 'Dark',
    'language': 'Language',
    'selectLanguage': 'Select app language',
    'temperature': 'Temperature',
    'weatherDisplayUnit': 'Weather display unit',
    'landArea': 'Land Area',
    'farmSizeUnit': 'Farm size unit',
    'dataSaver': 'Data Saver',
    'reduceData': 'Reduce animations & image quality',
    'aboutApp': 'About App',
    'version': 'Version',
    'build': 'Build',
    'checkForUpdates': 'Check for Updates',

    // Existing Keys (Keep these)
    'manageAccount': 'Manage Account',
    'profileInformation': 'Profile Information',
    'phoneNumber': 'Phone Number',
    'email': 'Email',
    'farmLocation': 'Farm Location',
    'farmSize': 'Farm Size',
    'languageSettings': 'Language Settings',
    'primaryLanguage': 'Primary Language',
    'secondaryLanguage': 'Secondary Language',
    'voiceCommands': 'Voice Commands',
    'enableVoice': 'Enable voice input in selected language',
    'notificationPreferences': 'Notification Preferences',
    'privacySecurity': 'Privacy & Security',
    'accountSecurity': 'Account Security',
    'yourAccountSecure': 'Your account is secure',
    'verified': 'Verified',
    'twoFactor': 'Two-Factor Authentication',
    'addExtraSecurity': 'Add extra security to your account',
    'dataSharing': 'Data Sharing',
    'shareData': 'Share anonymous data for research',
    'locationServices': 'Location Services',
    'forWeather': 'For weather and local recommendations',
    'changePassword': 'Change Password',
    'downloadData': 'Download My Data',
    'deleteAccount': 'Delete Account',
    'saveChanges': 'Save Changes',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'verifiedFarmer': 'Verified Farmer',
    'weatherAlerts': 'Weather Alerts',
    'severeWeather': 'Severe weather and rain predictions',
    'irrigationReminders': 'Irrigation Reminders',
    'wateringSchedule': 'Watering schedule notifications',
    'cropHealthUpdates': 'Crop Health Updates',
    'diseaseAlerts': 'Disease alerts and recommendations',
    'marketPriceUpdates': 'Market Price Updates',
    'dailyCommodity': 'Daily commodity price changes',
    'communityActivity': 'Community Activity',
    'forumDiscussions': 'Forum discussions and replies',
    'greenPointsUpdates': 'Green Points Updates',
    'achievementUpdates': 'Achievement and ranking updates',
    'communityHub': 'Community Hub',
    'communityPoll': 'Community Poll',
    'recentDiscussions': 'Recent Discussions',
    'startDiscussion': 'Start a Discussion',
    'viewAllDiscussions': 'View All Discussions',
    'farmingTips': 'Farming Tips',
    'achievements': 'Achievements',
    'viewAllAchievements': 'View All Achievements',
    'vote': 'Vote',
    'post': 'Post',
    'postTitle': 'Post Title',
    'postContent': 'What do you want to talk about?',
    'newDiscussion': 'Start a New Discussion',
    'marketPrices': 'Market Prices (Mandi Bhav)',
    'realTimePrices': 'Real-time commodity prices from major markets',
    'liveUpdates': 'Live Updates',
    'lastUpdated': 'Last updated',
    'searchCrops': 'Search crops (e.g., Onion, Wheat)...',
    'filterByMarket': 'Filter by Market',
    'allMarkets': 'All Markets',
    'commodityPrices': 'Commodity Prices',
    'crop': 'Crop',
    'market': 'Market',
    'price': 'Price (₹/Qtl)',
    'change': 'Change',
    'trend': 'Trend',
    'noCropsFound': 'No crops found matching your search.',

    // Help Page
    'helpCenter': 'Help Center',
    'searchHelp': 'Search Help Articles',
    'searchPlaceholder': 'Search for help articles, guides, and tutorials...',
    'popularSearches': 'Popular searches',
    'faq': 'Frequently Asked Questions',
    'viewAllFaq': 'View All FAQs',
    'learningResources': 'Learning Resources',
    'videoTutorials': 'Video Tutorials',
    'learnWithGuides': 'Learn with step-by-step guides',
    'watchNow': 'Watch Now',
    'quickHelp': 'Quick Help',
    'voiceAssistant': 'Voice Assistant',
    'askInLocal': 'Ask questions in your local language',
    'startVoiceChat': 'Start Voice Chat',
    'liveChat': 'Live Chat Support',
    'getInstantHelp': 'Get instant help from our experts',
    'startChat': 'Start Chat',
    'contactSupport': 'Contact Support',
    'helpline': 'Helpline',
    'emailSupport': 'Email Support',
    'available247': 'Available 24/7',
    'responseTime': 'Response in 2-4 hours',
    'allFaq': 'All Frequently Asked Questions',
    'faq1_q': 'How do I add a new crop to monitor?',
    'faq1_a': "From the Dashboard, navigate to the 'My Crops' section and click the 'Add Crop' button. You can then select your crop type, planting date, and other relevant details.",
    'faq2_q': 'Why is my soil moisture reading inaccurate?',
    'faq2_a': 'Inaccurate readings can be caused by improper sensor placement or calibration issues. Ensure the sensor is inserted to the correct depth and recalibrate it through the device settings. Contact support if the issue persists.',
    'faq3_q': 'How to interpret weather predictions?',
    'faq3_a': 'Our weather module provides forecasts for temperature, humidity, rainfall, and wind speed. Pay attention to the hourly and daily trends to plan your farming activities like irrigation and pesticide application.',
    'faq4_q': 'Setting up irrigation schedules',
    'faq4_a': "In the 'Irrigation' tab, you can create custom schedules based on crop type and soil moisture levels. The system can also suggest optimal watering times based on weather data to conserve water.",
    'faq5_q': 'How are Green Points calculated?',
    'faq5_a': 'Green Points are awarded for sustainable farming practices, such as conserving water, using organic fertilizers, and participating in community discussions. The more sustainable your actions, the more points you earn.',
  },
  hindi: {
    // Navigation
    'navHome': 'होम',
    'navCrops': 'फसल और सिंचाई',
    'navDisease': 'रोग पहचान (AI)',
    'navCommunity': 'सामुदायिक केंद्र',
    'navMarket': 'बाजार भाव',
    'navHelp': 'सहायता केंद्र',
    'navAccount': 'खाता प्रबंधन',
    'navSettings': 'सेटिंग्स',
    'navLogout': 'लॉग आउट',
    'menu': 'मेन्यू',

    // Dashboard
    'farmDashboard': 'फार्म डैशबोर्ड',
    'weatherAQI': 'मौसम और AQI',
    'soilHealth': 'मिट्टी का स्वास्थ्य',
    'aiCropRec': 'AI फसल सिफारिशें',
    'rainfall': 'वर्षा',
    'aqi': 'AQI',
    'moistureLevel': 'नमी का स्तर',
    'fertilityIndex': 'उर्वरता सूचकांक',
    'viewLess': 'कम देखें',
    'viewAllRec': 'सभी सिफारिशें देखें',
    'selectSeason': 'मौसम चुनें',
    'summer': 'गर्मी',
    'monsoon': 'मानसून',
    'winter': 'सर्दी',

    // Crops Page
    'cropIrrigationRec': 'फसल और सिंचाई सिफारिशें',
    'currentSeasonCrops': 'वर्तमान मौसम की फसलें',
    'irrigationZones': 'सिंचाई क्षेत्र',
    'growthTracking': 'विकास ट्रैकिंग',
    'smartRec': 'स्मार्ट सिफारिशें',
    'match': 'मेल',
    'suitability': 'उपयुक्तता',
    'nextWatering': 'अगली सिंचाई',
    'adjust': 'समायोजित करें',
    'active': 'सक्रिय',
    'scheduled': 'अनुसूचित',
    'manual': 'मैनुअल',
    'yieldPrediction': 'उपज भविष्यवाणी',
    'expectedHarvest': 'अनुमानित कटाई',
    'days': 'दिनों में',
    'growthRate': 'विकास दर',
    'healthScore': 'स्वास्थ्य स्कोर',
    'todaysAction': 'आज की कार्रवाई',
    'harvestReady': 'कटाई के लिए तैयार',

    // Disease Detection
    'cropDiseaseDetection': 'फसल रोग पहचान (AI)',
    'uploadImage': 'छवि अपलोड करें',
    'clickToUpload': 'अपलोड करने के लिए क्लिक करें या ड्रैग करें',
    'supportsFormats': 'JPG, PNG समर्थित',
    'analyzeCrop': 'फसल का विश्लेषण करें',
    'analyzing': 'विश्लेषण कर रहा है...',
    'analysisResult': 'विश्लेषण परिणाम',
    'severity': 'गंभीरता',
    'confidence': 'आत्मविश्वास',
    'recommendedTreatment': 'अनुशंसित उपचार',
    'disclaimer': 'अस्वीकरण: यह एक AI सिमुलेशन है। महत्वपूर्ण निर्णयों के लिए हमेशा विशेषज्ञ से सलाह लें।',

    // Settings
    'settings': 'सेटिंग्स',
    'appearanceLanguage': 'दिखावट और भाषा',
    'unitsMeasurements': 'इकाइयाँ और माप',
    'appPreferences': 'ऐप प्राथमिकताएं',
    'appTheme': 'ऐप थीम',
    'selectTheme': 'अपना पसंदीदा डिस्प्ले मोड चुनें',
    'light': 'लाइट',
    'dark': 'डार्क',
    'language': 'भाषा',
    'selectLanguage': 'ऐप भाषा चुनें',
    'temperature': 'तापमान',
    'weatherDisplayUnit': 'मौसम प्रदर्शन इकाई',
    'landArea': 'भूमि क्षेत्र',
    'farmSizeUnit': 'खेत का आकार इकाई',
    'dataSaver': 'डेटा सेवर',
    'reduceData': 'एनिमेशन और छवि गुणवत्ता कम करें',
    'aboutApp': 'ऐप के बारे में',
    'version': 'संस्करण',
    'build': 'बिल्ड',
    'checkForUpdates': 'अपडेट के लिए जाँच करें',

    // Help Page
    'helpCenter': 'सहायता केंद्र',
    'searchHelp': 'सहायता लेख खोजें',
    'searchPlaceholder': 'सहायता लेख, गाइड और ट्यूटोरियल खोजें...',
    'popularSearches': 'लोकप्रिय खोजें',
    'faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'viewAllFaq': 'सभी प्रश्न देखें',
    'learningResources': 'सीखने के संसाधन',
    'videoTutorials': 'वीडियो ट्यूटोरियल',
    'learnWithGuides': 'चरण-दर-चरण गाइड के साथ सीखें',
    'watchNow': 'अभी देखें',
    'quickHelp': 'त्वरित सहायता',
    'voiceAssistant': 'वॉयस असिस्टेंट',
    'askInLocal': 'अपनी स्थानीय भाषा में प्रश्न पूछें',
    'startVoiceChat': 'वॉयस चैट शुरू करें',
    'liveChat': 'लाइव चैट सपोर्ट',
    'getInstantHelp': 'हमारे विशेषज्ञों से तुरंत मदद प्राप्त करें',
    'startChat': 'चैट शुरू करें',
    'contactSupport': 'संपर्क सहायता',
    'helpline': 'हेल्पलाइन',
    'emailSupport': 'ईमेल सहायता',
    'available247': '24/7 उपलब्ध',
    'responseTime': '2-4 घंटे में जवाब',
    'allFaq': 'सभी अक्सर पूछे जाने वाले प्रश्न',
    'faq1_q': 'मैं निगरानी के लिए नई फसल कैसे जोड़ूं?',
    'faq1_a': "डैशबोर्ड से, 'मेरी फसलें' अनुभाग पर जाएं और 'फसल जोड़ें' बटन पर क्लिक करें। फिर आप अपनी फसल का प्रकार, रोपण तिथि और अन्य प्रासंगिक विवरण चुन सकते हैं।",
    'faq2_q': 'मेरी मिट्टी की नमी की रीडिंग गलत क्यों है?',
    'faq2_a': 'गलत रीडिंग अनुचित सेंसर प्लेसमेंट या अंशांकन मुद्दों के कारण हो सकती है। सुनिश्चित करें कि सेंसर सही गहराई तक डाला गया है और डिवाइस सेटिंग्स के माध्यम से इसे फिर से कैलिब्रेट करें। यदि समस्या बनी रहती है तो समर्थन से संपर्क करें।',
    'faq3_q': 'मौसम की भविष्यवाणियों की व्याख्या कैसे करें?',
    'faq3_a': 'हमारा मौसम मॉड्यूल तापमान, आर्द्रता, वर्षा और हवा की गति के लिए पूर्वानुमान प्रदान करता है। सिंचाई और कीटनाशक आवेदन जैसी अपनी खेती की गतिविधियों की योजना बनाने के लिए प्रति घंटा और दैनिक रुझानों पर ध्यान दें।',
    'faq4_q': 'सिंचाई कार्यक्रम स्थापित करना',
    'faq4_a': "'सिंचाई' टैब में, आप फसल के प्रकार और मिट्टी की नमी के स्तर के आधार पर कस्टम शेड्यूल बना सकते हैं। सिस्टम पानी बचाने के लिए मौसम के आंकड़ों के आधार पर इष्टतम पानी के समय का सुझाव भी दे सकता है।",
    'faq5_q': 'ग्रीन पॉइंट्स की गणना कैसे की जाती है?',
    'faq5_a': 'ग्रीन पॉइंट्स टिकाऊ खेती प्रथाओं के लिए दिए जाते हैं, जैसे पानी बचाना, जैविक उर्वरकों का उपयोग करना और सामुदायिक चर्चाओं में भाग लेना। आपके कार्य जितने अधिक टिकाऊ होंगे, आप उतने ही अधिक अंक अर्जित करेंगे।',

    // Existing Keys (Keep these)
    'manageAccount': 'खाता प्रबंधित करें',
    'profileInformation': 'प्रोफ़ाइल जानकारी',
    'phoneNumber': 'फ़ोन नंबर',
    'email': 'ईमेल',
    'farmLocation': 'खेत का स्थान',
    'farmSize': 'खेत का आकार',
    'languageSettings': 'भाषा सेटिंग्स',
    'primaryLanguage': 'प्राथमिक भाषा',
    'secondaryLanguage': 'द्वितीयक भाषा',
    'voiceCommands': 'वॉयस कमांड',
    'enableVoice': 'चयनित भाषा में वॉयस इनपुट सक्षम करें',
    'notificationPreferences': 'अधिसूचना प्राथमिकताएं',
    'privacySecurity': 'गोपनीयता और सुरक्षा',
    'accountSecurity': 'खाता सुरक्षा',
    'yourAccountSecure': 'आपका खाता सुरक्षित है',
    'verified': 'सत्यापित',
    'twoFactor': 'दो-चरण प्रमाणीकरण',
    'addExtraSecurity': 'अपने खाते में अतिरिक्त सुरक्षा जोड़ें',
    'dataSharing': 'डेटा साझाकरण',
    'shareData': 'अनुसंधान के लिए अनाम डेटा साझा करें',
    'locationServices': 'स्थान सेवाएं',
    'forWeather': 'मौसम और स्थानीय सिफारिशों के लिए',
    'changePassword': 'पासवर्ड बदलें',
    'downloadData': 'मेरा डेटा डाउनलोड करें',
    'deleteAccount': 'खाता हटाएं',
    'saveChanges': 'परिवर्तन सहेजें',
    'cancel': 'रद्द करें',
    'edit': 'संपादित करें',
    'verifiedFarmer': 'सत्यापित किसान',
    'weatherAlerts': 'मौसम अलर्ट',
    'severeWeather': 'गंभीर मौसम और बारिश की भविष्यवाणी',
    'irrigationReminders': 'सिंचाई अनुस्मारक',
    'wateringSchedule': 'पानी देने का कार्यक्रम सूचनाएं',
    'cropHealthUpdates': 'फसल स्वास्थ्य अपडेट',
    'diseaseAlerts': 'रोग अलर्ट और सिफारिशें',
    'marketPriceUpdates': 'बाजार मूल्य अपडेट',
    'dailyCommodity': 'दैनिक वस्तु मूल्य परिवर्तन',
    'communityActivity': 'समुदाय गतिविधि',
    'forumDiscussions': 'मंच चर्चा और जवाब',
    'greenPointsUpdates': 'ग्रीन पॉइंट्स अपडेट',
    'achievementUpdates': 'उपलब्धि और रैंकिंग अपडेट',
    'communityHub': 'सामुदायिक केंद्र',
    'communityPoll': 'सामुदायिक सर्वेक्षण',
    'recentDiscussions': 'हाल की चर्चाएं',
    'startDiscussion': 'चर्चा शुरू करें',
    'viewAllDiscussions': 'सभी चर्चाएं देखें',
    'farmingTips': 'खेती के सुझाव',
    'achievements': 'उपलब्धियां',
    'viewAllAchievements': 'सभी उपलब्धियां देखें',
    'vote': 'वोट दें',
    'post': 'पोस्ट करें',
    'postTitle': 'पोस्ट शीर्षक',
    'postContent': 'आप किस बारे में बात करना चाहते हैं?',
    'newDiscussion': 'नई चर्चा शुरू करें',
    'marketPrices': 'बाजार भाव (मंडी भाव)',
    'realTimePrices': 'प्रमुख बाजारों से वास्तविक समय की वस्तुओं की कीमतें',
    'liveUpdates': 'लाइव अपडेट',
    'lastUpdated': 'अंतिम अपडेट',
    'searchCrops': 'फसलें खोजें (जैसे, प्याज, गेहूं)...',
    'filterByMarket': 'बाजार द्वारा फ़िल्टर करें',
    'allMarkets': 'सभी बाजार',
    'commodityPrices': 'वस्तु कीमतें',
    'crop': 'फसल',
    'market': 'बाजार',
    'price': 'कीमत (₹/क्विंटल)',
    'change': 'परिवर्तन',
    'trend': 'रुझान',
    'noCropsFound': 'आपकी खोज से मेल खाने वाली कोई फसल नहीं मिली।',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('english');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
